### ISSUE TITLE
Missing egg file

### ISSUE THREAD

**Issue by halkeye** [metrogamelab/stardew-valley-mods#1]
Readme says:

> Use the egg file and set the Steam varialbes.

Which file is the egg file? Is that elsewhere? none of the json files look like eggs.

**Comment by halkeye** [comment]
ah, is it this repo? https://github.com/metrogamelab/stardew-valley-server

**Comment by hirata-estate** [comment]
bump

**Comment by trentnbauer** [comment]
bump

**Comment by halkeye** [comment]
What do you expect bump to do?

**Comment by trentnbauer** [comment]
Hopefully a copy of the file!
